version: '3.5'

services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    env_file:
      - .env_ganache # Set this to the forked ganache env and set the ganache command to `--defaultBalanceEther --fork INSERT_RPC_ADDRESS -d`
    depends_on:
      - db
      - redis
    working_dir: /app
    ports:
      - "8888:8888"
    volumes:
      - nginx-shared:/nginx
      - ./safe_relay_service:/app/safe_relay_service
      - ./config:/app/config
    command: docker/web/run_web.sh

  worker: &worker
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    env_file:
      - .env_ganache
    volumes:
      - ./safe_relay_service:/app/safe_relay_service
      - ./config:/app/config
    depends_on:
      - db
      - redis
    command: docker/web/celery/worker/run.sh

  ganache:
    image: trufflesuite/ganache:latest
    command: --defaultBalanceEther 10000 --gasLimit 10000000 -a 30 --chain.chainId 1337 --chain.networkId 1337 -d
    ports:
      - "8545:8545"
